config/routes.rb
TaskApp::Application.routes.draw do
  get "categories/new"

  resources :users, :only => [:edit, :update, :destroy]
  
  resources :tasks
  
  root :to=> 'static_pages#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence=>true, :length=> { :maximum => 25 }
  has_many :user_categories
  has_many :users, :through => :user_categories
end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
  attr_accessible :name, :complete
  belongs_to :task

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :task_name, :category_id, :due_date, :complete, :priority, :description
  belongs_to :user
  has_many :subtask
  has_one :category

  validates :task_name, :presence=>true, :length=> { :maximum=>140 }
  validates :user_id, :presence=>true
  # validates :category, :presence=>true # if there "isn't a category", it'll be none as default
  #category, due date is optional  

  # CATEGORY = [['None',1],['Class', 2],['Work', 3]]
  #  CATEGORY = Hash['None' => 1,'Class' => 2, 'Work' => 3]
  # can make a new array of keys by CATEGORY.keys, .values (values)
  # don't use .shift  --removes stuff randomy

  PRIORITY = Hash['High'=>1, 'Medium' => 2, 'Low' => 3]
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :first_name, :last_name, :active_user
  has_many :tasks
  has_many :user_categories
  has_many :categories, :through => :user_categories
  after_save { validates_presence_of :first_name, :last_name }
 # validates :first_name, :last_name,  :presence=>true, :length=> { :maximum=> 25 }, :unless=>User.new() {|r| r.user}
end

app/models/user_category.rb
class UserCategory < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  attr_accessible :name, :user_id, :category_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include CasAuthentication
  before_filter :login_required

#  def find_user_by_username(username)
#    user = User.find_or_initialize_by_username((session[:cas_user]).upcase) 
#    if user.active_user == nil && user.first_name == nil && user.last_name == nil
#      person = PersonRecord::Person.find_by_username session[:cas_user].upcase
#      user.first_name = person.first_and_middle_name.split(" ").first
#      user.last_name = person.last_name
#      user.active_user = true
#      user.save!
#    end
#      user.active_user = true
#      user.save!
    
#    user
#  end  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end
  
  def show
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      flash[:success] = "created category"
      redirect_to show_task_path
    else
      render 'new'
    end
  end

  def update
  end

  def destroy
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end

  def current_user
  end

  def show_tasks
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
     @tasks = @user.tasks
  end

  def show
    @tasks= current_user.tasks 
  end

  def new
    @task = Task.new
  end

  def create      
    @task = current_user.tasks.build(params[:task])
    if @task.save
      flash[:success] = "Task Created"
      redirect_to tasks_url
    else
      render new_task
    end
  end

  def edit
    @task = Task.find params[:id]
  end

  def update
  end
  
  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      redirect_to edit_user_path(@user)
    else
      render 'edit'
    end
  end

  def show

  end

  def destroy

  end

end                                                                         

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.
     def full_title(page_title)
         base_title = "The Task Manager"
             if page_title.empty?
                   base_title
             else
               "#{base_title} | #{page_title}"
            end
     end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"> 
    <h1><a href="#"><%= link_to "Home", root_path%></a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

   <section class="top-bar-section">
   <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><a href="#"><%= link_to "Tasks", task_path(@current_user) %></a></li>
      <li class="active"><a href="#"><%= link_to "Settings", edit_user_path(@current_user) %>
      </a></li>
    </ul>
  </section>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="side-bar">
  <p>  Organize by: </p>
  <ul class="side-nav">
    <li><a href="#">Priority</a></li>
    <li><a href="#">Category</a></li>
    <li><a href="#">Due Date</a></li>
    <li><a href="#">Alphabetical</a></li>
    <li><a href="#"><%= link_to "New Task", new_task_path %></a></li>
  </ul>
</div>

app/views/layouts/_tasks.html.erb
<div>
  <%= simple_form_for @task do |f| %>
    <%= f.input :task_name %>
    <%= collection_select(:category) %>
    <%= f.input :description %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>  
<%= yield %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div>
    <div>
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<!DOCTYPE html>
<h1> The Task Manager</h1>
<p> This is the home page for the Work Organizer </p>

app/views/tasks/_form.html.erb
<!-- This is where the form will be made for edit/new Task --> 
<%= form_for(@task) do |task| %>
  <%= task.label :task_Name %>
  <%= task.text_field :task_name %>

  <%= task.label :category %>
  <%= collection_select(:task, :category, @current_user.categories, :id, :name, :prompt=>true) %>

  <%= task.label :description %>
  <%= text_area(:task, :description)    %>

  <!--  <%= task.label :Subtasks %>  -->
  <!-- <%= task.text_field :subtask %> -->

  <%= task.button :submit %>
<% end %> 

app/views/tasks/_task.html.erb
<div class="row">
  <div class="small-2 large-4 columns"><%= task.task_name %> </div>
  <!-- Here will actually be the progress bar--> 
  <div class="small-4 large-4 columns"><%= Category.find(task.category_id).name%></div>
  <div class="small-6 large-4 columns"><%= task.due_date %></div>
</div>

app/views/tasks/index.html.erb
<%= render 'layouts/sidebar' %>
<% provide(:title, "Tasks") %>
<div id="task-container">
  <h1> Tasks </h1>
  <p> here we will loop out the Tasks </p>
</div>

app/views/tasks/new.html.erb
<% provide(:title, "New Task") %>
<h1> New Task </h1>

<%= render 'tasks/form' %>

app/views/tasks/show.html.erb
<%= render 'layouts/sidebar' %>
<div id="tasks_Container">
  <div class="row" id="task_header">
    <div class="small-2 large-4 columns">Task</div>
    <!-- Here will actually be the progress bar--> 
    <div class="small-4 large-4 columns">Progress</div>
    <div class="small-6 large-4 columns">Due Date</div>
  </div>
  <%= render @tasks %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<div id="edit-form">
  <%= simple_form_for @user do |user| %>
    <%= user.input :first_name, :label=>"First Name" %>
    <%= user.input :last_name, :label=> "Last Name" %>
    <%= user.button :submit %>
  <% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Edit User Information') %>

<h1>Update your profile</h1>

<div class="row">
</div>